version: '3.1'

services:
  app:
    build: ./
    command: npm run start
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on: 
      - mongodb
    environment:
      MONGO_DB_URL: mongodb://root:example@mongodb:27017/
      MONGO_DB_USER: root
      MONGO_DB_PASSWORD: example

  mongodb:
    image: mongo:5.0.9
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example