version: '3.1'

services:
  app:
    build: ./
    command: npm run start
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    expose:
      - "3000"
    depends_on: 
      - mongodb
    environment:
      MONGO_DB_URL: mongodb://root:example@mongodb:27017/
      MONGO_DB_USER: root
      MONGO_DB_PASSWORD: example

  mongodb:
    image: mongo:5.0.9
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    ports:
      - "8081:80"
      - "8324:443"
    depends_on:
      - app
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/conf:/etc/letsencrypt/conf
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
